In [14]:
import numpy as np
import pandas as pd
import os
import matplotlib.pyplot as plt
from collections import defaultdict

In [6]:
def archivo_no_vacio(fpath):  
    return True if os.path.isfile(fpath) and os.path.getsize(fpath) > 0 else False

In [16]:
empresas_df =  pd.read_csv("constituents_csv.csv", sep=",")
empresas_df["Symbol"] = empresas_df["Symbol"].str.lower()
lista_sectores = list(empresas_df["Sector"])
dic_empresas_industria = defaultdict()
for index, accion in enumerate(empresas_df["Symbol"]):
    dic_empresas_industria[accion] = lista_sectores[index]

In [18]:
# filtro de fechas y filtro de empresas grandes#
data_unico = []
list_files = os.listdir("Stocks1/")
for csv in list_files:
    path = f"Stocks1/{csv}"
    index = csv.find(".us")
    simple = csv[0:index]
    if simple not in list(empresas_df["Symbol"]):
        continue
    # recorremos los archivos no vacios
    if archivo_no_vacio(path):
        df = pd.read_csv(path, sep=",")
        df = df[['Date', 'Open', 'Close', 'Volume']]
        df['ticker'] = csv.replace('.csv', '')
        df['Rendimiento'] = (df['Close'] - df['Open']) / df['Open']
        # filtramos para obtener los datos de hasta el 31 Dic de 2014
        df = df[(df['Date'] < '2015-01-01 00:00:00')]
        
        # filtramos por presencia bursatil
        if len(df.index)/ 1258 < 0.999:      # permitimos 1 dia de no presencia, 1258 es el maximo de presencias
            continue   # no la consideramos
        # si tiene suficiente presencia bursatil la consideramos
        data_unico.append(df)
data_unico = pd.concat(data_unico, ignore_index=True)
data_unico.reset_index(inplace=True, drop=True)
data_unico

              Date    Open   Close   Volume  ticker  Rendimiento
0       2010-01-04  21.245  21.128  4043084    a.us    -0.005507
1       2010-01-05  21.067  20.899  4435651    a.us    -0.007975
2       2010-01-06  20.899  20.825  3437283    a.us    -0.003541
3       2010-01-07  20.777  20.798  3279988    a.us     0.001011
4       2010-01-08  20.683  20.791  3956596    a.us     0.005222
...            ...     ...     ...      ...     ...          ...
577820  2014-12-24  42.090  42.855  1330548  zts.us     0.018175
577821  2014-12-26  42.815  43.206  1552946  zts.us     0.009132
577822  2014-12-29  43.030  43.021  2053391  zts.us    -0.000209
577823  2014-12-30  42.992  42.376  2302907  zts.us    -0.014328
577824  2014-12-31  42.543  42.062  2198321  zts.us    -0.011306

[577825 rows x 6 columns]

In [10]:
# filtro de fechas solamente#
data_unico = []
list_files = os.listdir("Stocks1/")
for csv in list_files:
    path = f"Stocks1/{csv}"
    index = csv.find(".us")
    simple = csv[0:index]
#     if simple not in list(empresas_df["Symbol"]):
#         continue
    # recorremos los archivos no vacios
    if archivo_no_vacio(path):
        df = pd.read_csv(path, sep=",")
        df = df[['Date', 'Open', 'Close', 'Volume']]
        df['ticker'] = csv.replace('.csv', '')
        df['Rendimiento'] = (df['Close'] - df['Open']) / df['Open']
        # filtramos para obtener los datos de hasta el 31 Dic de 2014
        df = df[(df['Date'] < '2015-01-01 00:00:00')]
        data_unico.append(df)
data_unico = pd.concat(data_unico, ignore_index=True)
data_unico.reset_index(inplace=True, drop=True)
data_unico

               Date    Open   Close   Volume       ticker  Rendimiento
0        2010-01-04  21.245  21.128  4043084     a.us.csv    -0.005507
1        2010-01-05  21.067  20.899  4435651     a.us.csv    -0.007975
2        2010-01-06  20.899  20.825  3437283     a.us.csv    -0.003541
3        2010-01-07  20.777  20.798  3279988     a.us.csv     0.001011
4        2010-01-08  20.683  20.791  3956596     a.us.csv     0.005222
...             ...     ...     ...      ...          ...          ...
9416055  2017-11-06  10.420  11.190   977948  zyne.us.csv     0.073896
9416056  2017-11-07  11.300  10.830   451210  zyne.us.csv    -0.041593
9416057  2017-11-08  10.700  10.900   336449  zyne.us.csv     0.018692
9416058  2017-11-09  11.000  11.600   463067  zyne.us.csv     0.054545
9416059  2017-11-10  11.680  12.460   885587  zyne.us.csv     0.066781

[9416060 rows x 6 columns]

In [9]:
# contando
todos = list(data_unico["ticker"])
vacia = []
contador = 0
for elemento in todos:
    if elemento not in vacia:
        contador += 1
        vacia.append(elemento)
print(contador)

486

In [11]:
## covarianza con datos diarios

In [17]:
 ## covarianza con datos diarios
data_unico.dropna(subset=['Rendimiento'], inplace=True)